### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by Torotv** [VutonDesign/Homepage#4]

**Comment by VutonDesign** [comment]
Thanks

**Comment by Torotv** [comment]
Can you help me??

**Comment by VutonDesign** [comment]
With what?

**Comment by Torotv** [comment]
My website. I want it like somethibg great likd yours. Or shesank.com or blah blah blah whatever.

**Comment by Torotv** [comment]
I fork.your projects to test them but okay!

**Comment by VutonDesign** [comment]
@Torotv Yeah but they are not forks, they are copies.
Btw use https://html5up.net/

**Comment by Torotv** [comment]
Yeah but xan you help witb the pages and everything else on my sote or give me examples or tips.

**Comment by VutonDesign** [comment]
@Torotv Sorry, I don't have any time.

**Comment by Torotv** [comment]
Can i copy or use some of ypurs and give credit?

**Comment by VutonDesign** [comment]
@Torotv What exactly would you use from it?

**Comment by Torotv** [comment]
Some Code and Pages OR Maybe javasprcit or other Pages. OR just CSS.

**Comment by VutonDesign** [comment]
@Torotv I'd rather you didn't use them.
